#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SoloFi.Droid.Resource", IsApplication=true)]

namespace SoloFi.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::SoloFi.Droid.Resource.String.library_name;
			global::PCLCrypto.Resource.String.ApplicationName = global::SoloFi.Droid.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::SoloFi.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::SoloFi.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::SoloFi.Droid.Resource.String.Hello;
			global::XamlingCore.Droid.Resource.String.ApplicationName = global::SoloFi.Droid.Resource.String.ApplicationName;
			global::XamlingCore.Droid.Resource.String.Hello = global::SoloFi.Droid.Resource.String.Hello;
			global::XamlingCore.Droid.Resource.String.library_name = global::SoloFi.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int addtofavs = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int back = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bluetooth = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int calendar = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int close = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cloudsearch = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int delete = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int edit = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int favs = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int filtericon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int globe = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int leave = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int magnify = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int next = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int questionmark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int rlist = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int save = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int search = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int settings = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int library_name = 2130903042;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
